server:
  port: 8080
#db
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  mvc:
    static-path-pattern: /static/**
  datasource:
    first:
      username: root
      password: 980529
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.102.118.146:3306/lab_manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  file:
    name: lab_manage.log